"""add mock data

Revision ID: your_revision_id
Revises: previous_revision_id
Create Date: 2025-10-22 13:33:33.0001231

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta
from argon2 import PasswordHasher

# revision identifiers, used by Alembic.
revision = '1d967b395dae'
down_revision = 'ca1d8ef5cced'
branch_labels = None
depends_on = None

ph = PasswordHasher()

def hash_password(password: str) -> str:
    return ph.hash(password)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    users_table = sa.table('users',
        sa.column('id', sa.Integer),
        sa.column('username', sa.String),
        sa.column('password', sa.String),
        sa.column('github_id', sa.String),
        sa.column('is_author', sa.Boolean),
        sa.column('is_admin', sa.Boolean),
        sa.column('name', sa.String),
        sa.column('email', sa.String),
        sa.column('date', sa.DateTime),
        sa.column('ava', sa.LargeBinary),
        sa.column('is_active', sa.Boolean)
    )
    
    op.bulk_insert(users_table,
        [
            {
                'username': 'admin',
                'password': hash_password('admin'),
                'github_id': None,
                'is_author': True,
                'is_admin': True,
                'name': 'Администратор',
                'email': 'admin@example.com',
                'date': datetime.now() - timedelta(days=30),
                'ava': None,
                'is_active': True
            },
            {
                'username': 'author1',
                'password': hash_password('author1'),
                'github_id': None,
                'is_author': True,
                'is_admin': False,
                'name': 'Автор Первый',
                'email': 'author1@example.com',
                'date': datetime.now() - timedelta(days=25),
                'ava': None,
                'is_active': True
            },
            {
                'username': 'author2',
                'password': hash_password('author2'),
                'github_id': None,
                'is_author': True,
                'is_admin': False,
                'name': 'Автор Второй',
                'email': 'author2@example.com',
                'date': datetime.now() - timedelta(days=20),
                'ava': None,
                'is_active': True
            },
            {
                'username': 'user1',
                'password': hash_password('user1'),
                'github_id': 'github_user1',
                'is_author': False,
                'is_admin': False,
                'name': 'Пользователь Один',
                'email': 'user1@example.com',
                'date': datetime.now() - timedelta(days=15),
                'ava': None,
                'is_active': True
            },
            {
                'username': 'user2',
                'password': hash_password('user2'),
                'github_id': None,
                'is_author': False,
                'is_admin': False,
                'name': 'Пользователь Два',
                'email': 'user2@example.com',
                'date': datetime.now() - timedelta(days=10),
                'ava': None,
                'is_active': True
            }
        ]
    )
    

    news_table = sa.table('news',
        sa.column('id', sa.Integer),
        sa.column('header', sa.String),
        sa.column('content', sa.JSON),
        sa.column('date', sa.DateTime),
        sa.column('author_id', sa.Integer),
        sa.column('cover', sa.LargeBinary)
    )
    
    op.bulk_insert(news_table,
        [
            {
                'header': 'Первая новость',
                'content': {'blocks': [{'type': 'paragraph', 'data': {'text': 'Это содержание первой новости'}}]},
                'date': datetime.now() - timedelta(days=7),
                'author_id': 2,  
                'cover': None
            },
            {
                'header': 'Вторая новость о технологиях',
                'content': {'blocks': [{'type': 'paragraph', 'data': {'text': 'Новости о последних технологических достижениях'}}]},
                'date': datetime.now() - timedelta(days=6),
                'author_id': 3, 
                'cover': None
            },
            {
                'header': 'Третья новость - обновление системы',
                'content': {'blocks': [{'type': 'paragraph', 'data': {'text': 'Важное обновление нашей платформы'}}]},
                'date': datetime.now() - timedelta(days=5),
                'author_id': 2,  
                'cover': None
            },
            {
                'header': 'Четвертая новость от администрации',
                'content': {'blocks': [{'type': 'paragraph', 'data': {'text': 'Официальное заявление от администрации сайта'}}]},
                'date': datetime.now() - timedelta(days=4),
                'author_id': 1, 
                'cover': None
            },
            {
                'header': 'Пятая новость - будущие планы',
                'content': {'blocks': [{'type': 'paragraph', 'data': {'text': 'Наши планы по развитию на ближайший год'}}]},
                'date': datetime.now() - timedelta(days=3),
                'author_id': 3,  
                'cover': None
            }
        ]
    )
    

    comments_table = sa.table('comments',
        sa.column('id', sa.Integer),
        sa.column('text', sa.Text),
        sa.column('news_id', sa.Integer),
        sa.column('date', sa.DateTime),
        sa.column('author_id', sa.Integer)
    )
    
    op.bulk_insert(comments_table,
        [
            {
                'text': 'Отличная новость! Спасибо за информацию.',
                'news_id': 1,
                'date': datetime.now() - timedelta(days=6, hours=2),
                'author_id': 4 
            },
            {
                'text': 'Интересная статья, жду продолжения.',
                'news_id': 1,
                'date': datetime.now() - timedelta(days=6, hours=1),
                'author_id': 5  
            },
            {
                'text': 'Есть вопросы по технической реализации.',
                'news_id': 2,
                'date': datetime.now() - timedelta(days=5, hours=3),
                'author_id': 4  
            },
            {
                'text': 'Очень полезное обновление!',
                'news_id': 3,
                'date': datetime.now() - timedelta(days=4, hours=5),
                'author_id': 5  
            },
            {
                'text': 'Согласен с автором, полностью поддерживаю.',
                'news_id': 4,
                'date': datetime.now() - timedelta(days=3, hours=1),
                'author_id': 4
            },
            {
                'text': 'Когда ждать реализации этих планов?',
                'news_id': 5,
                'date': datetime.now() - timedelta(days=2, hours=4),
                'author_id': 5  
            }
        ]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("DELETE FROM comments")
    op.execute("DELETE FROM news")
    op.execute("DELETE FROM sessions")
    op.execute("DELETE FROM users")
    
    # ### end Alembic commands ###
